export default defineAppConfig({
  pages: [
    'pages/index/index',
    'pages/login/index',
    'pages/alerts/index',
    'pages/devices/index',
    'pages/data/index',
    'pages/settings/index',
    'pages/export/index',
    'pages/health/index',
    'pages/messages/index',
    'pages/profile/index',
    'pages/records/index',
    'pages/settings/goals/index',
    'pages/settings/tracking/index',
    'pages/pin-overview/index',
    'pages/plan/index',
    'pages/plan/detail/index',
    'pages/credit/index',
    'pages/record/glucose/index',
    'pages/record/pressure/index',
    'pages/record/weight/index',
    'pages/record/heart-rate/index',
    'pages/record/temperature/index',
    'pages/record/spo2/index',
    'pages/record/medication/index',
    'pages/record/period/index',
    'pages/form/index',
    'pages/patient-select/index',
    'pages/form-list/index',
  ],
  window: {
    backgroundTextStyle: 'light',
    navigationBarBackgroundColor: '#416323',
    navigationBarTitleText: 'IOMTea',
    navigationBarTextStyle: 'white',
  },
  tabBar: {
    custom: true,
    list: [
      { pagePath: 'pages/index/index', text: '首页' },
      { pagePath: 'pages/health/index', text: '健康' },
      { pagePath: 'pages/messages/index', text: '消息' },
      { pagePath: 'pages/profile/index', text: '我的' },
    ],
  },
  permission: {
    'scope.userLocation': {
      desc: '需要获取您的位置信息用于设备定位',
    },
  },
})
