/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AuthIndexRouteImport } from './routes/_auth.index'
import { Route as AuthSimulationRouteImport } from './routes/_auth.simulation'
import { Route as AuthSettingsRouteImport } from './routes/_auth.settings'
import { Route as AuthPatientsRouteImport } from './routes/_auth.patients'
import { Route as AuthMedicationsRouteImport } from './routes/_auth.medications'
import { Route as AuthDataExportRouteImport } from './routes/_auth.data-export'
import { Route as AuthDataDashboardRouteImport } from './routes/_auth.data-dashboard'
import { Route as AuthAlertsRouteImport } from './routes/_auth.alerts'
import { Route as AuthSettingsUsersRouteImport } from './routes/_auth.settings.users'
import { Route as AuthPatientsIdRouteImport } from './routes/_auth.patients.$id'
import { Route as AuthIotPinsRouteImport } from './routes/_auth.iot.pins'
import { Route as AuthPatientsIdIndexRouteImport } from './routes/_auth.patients.$id.index'
import { Route as AuthPatientsIdProfileRouteImport } from './routes/_auth.patients.$id.profile'
import { Route as AuthPatientsIdMedicationsRouteImport } from './routes/_auth.patients.$id.medications'
import { Route as AuthPatientsIdMapEditorRouteImport } from './routes/_auth.patients.$id.map-editor'
import { Route as AuthPatientsIdHealthTimelineRouteImport } from './routes/_auth.patients.$id.health-timeline'
import { Route as AuthPatientsIdAlertsRouteImport } from './routes/_auth.patients.$id.alerts'
import { Route as AuthPatientsIdAlertRulesRouteImport } from './routes/_auth.patients.$id.alert-rules'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSimulationRoute = AuthSimulationRouteImport.update({
  id: '/simulation',
  path: '/simulation',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSettingsRoute = AuthSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthRoute,
} as any)
const AuthPatientsRoute = AuthPatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => AuthRoute,
} as any)
const AuthMedicationsRoute = AuthMedicationsRouteImport.update({
  id: '/medications',
  path: '/medications',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDataExportRoute = AuthDataExportRouteImport.update({
  id: '/data-export',
  path: '/data-export',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDataDashboardRoute = AuthDataDashboardRouteImport.update({
  id: '/data-dashboard',
  path: '/data-dashboard',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAlertsRoute = AuthAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSettingsUsersRoute = AuthSettingsUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthSettingsRoute,
} as any)
const AuthPatientsIdRoute = AuthPatientsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthPatientsRoute,
} as any)
const AuthIotPinsRoute = AuthIotPinsRouteImport.update({
  id: '/iot/pins',
  path: '/iot/pins',
  getParentRoute: () => AuthRoute,
} as any)
const AuthPatientsIdIndexRoute = AuthPatientsIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthPatientsIdRoute,
} as any)
const AuthPatientsIdProfileRoute = AuthPatientsIdProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthPatientsIdRoute,
} as any)
const AuthPatientsIdMedicationsRoute =
  AuthPatientsIdMedicationsRouteImport.update({
    id: '/medications',
    path: '/medications',
    getParentRoute: () => AuthPatientsIdRoute,
  } as any)
const AuthPatientsIdMapEditorRoute = AuthPatientsIdMapEditorRouteImport.update({
  id: '/map-editor',
  path: '/map-editor',
  getParentRoute: () => AuthPatientsIdRoute,
} as any)
const AuthPatientsIdHealthTimelineRoute =
  AuthPatientsIdHealthTimelineRouteImport.update({
    id: '/health-timeline',
    path: '/health-timeline',
    getParentRoute: () => AuthPatientsIdRoute,
  } as any)
const AuthPatientsIdAlertsRoute = AuthPatientsIdAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AuthPatientsIdRoute,
} as any)
const AuthPatientsIdAlertRulesRoute =
  AuthPatientsIdAlertRulesRouteImport.update({
    id: '/alert-rules',
    path: '/alert-rules',
    getParentRoute: () => AuthPatientsIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthIndexRoute
  '/login': typeof LoginRoute
  '/alerts': typeof AuthAlertsRoute
  '/data-dashboard': typeof AuthDataDashboardRoute
  '/data-export': typeof AuthDataExportRoute
  '/medications': typeof AuthMedicationsRoute
  '/patients': typeof AuthPatientsRouteWithChildren
  '/settings': typeof AuthSettingsRouteWithChildren
  '/simulation': typeof AuthSimulationRoute
  '/iot/pins': typeof AuthIotPinsRoute
  '/patients/$id': typeof AuthPatientsIdRouteWithChildren
  '/settings/users': typeof AuthSettingsUsersRoute
  '/patients/$id/alert-rules': typeof AuthPatientsIdAlertRulesRoute
  '/patients/$id/alerts': typeof AuthPatientsIdAlertsRoute
  '/patients/$id/health-timeline': typeof AuthPatientsIdHealthTimelineRoute
  '/patients/$id/map-editor': typeof AuthPatientsIdMapEditorRoute
  '/patients/$id/medications': typeof AuthPatientsIdMedicationsRoute
  '/patients/$id/profile': typeof AuthPatientsIdProfileRoute
  '/patients/$id/': typeof AuthPatientsIdIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/alerts': typeof AuthAlertsRoute
  '/data-dashboard': typeof AuthDataDashboardRoute
  '/data-export': typeof AuthDataExportRoute
  '/medications': typeof AuthMedicationsRoute
  '/patients': typeof AuthPatientsRouteWithChildren
  '/settings': typeof AuthSettingsRouteWithChildren
  '/simulation': typeof AuthSimulationRoute
  '/': typeof AuthIndexRoute
  '/iot/pins': typeof AuthIotPinsRoute
  '/settings/users': typeof AuthSettingsUsersRoute
  '/patients/$id/alert-rules': typeof AuthPatientsIdAlertRulesRoute
  '/patients/$id/alerts': typeof AuthPatientsIdAlertsRoute
  '/patients/$id/health-timeline': typeof AuthPatientsIdHealthTimelineRoute
  '/patients/$id/map-editor': typeof AuthPatientsIdMapEditorRoute
  '/patients/$id/medications': typeof AuthPatientsIdMedicationsRoute
  '/patients/$id/profile': typeof AuthPatientsIdProfileRoute
  '/patients/$id': typeof AuthPatientsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/_auth/alerts': typeof AuthAlertsRoute
  '/_auth/data-dashboard': typeof AuthDataDashboardRoute
  '/_auth/data-export': typeof AuthDataExportRoute
  '/_auth/medications': typeof AuthMedicationsRoute
  '/_auth/patients': typeof AuthPatientsRouteWithChildren
  '/_auth/settings': typeof AuthSettingsRouteWithChildren
  '/_auth/simulation': typeof AuthSimulationRoute
  '/_auth/': typeof AuthIndexRoute
  '/_auth/iot/pins': typeof AuthIotPinsRoute
  '/_auth/patients/$id': typeof AuthPatientsIdRouteWithChildren
  '/_auth/settings/users': typeof AuthSettingsUsersRoute
  '/_auth/patients/$id/alert-rules': typeof AuthPatientsIdAlertRulesRoute
  '/_auth/patients/$id/alerts': typeof AuthPatientsIdAlertsRoute
  '/_auth/patients/$id/health-timeline': typeof AuthPatientsIdHealthTimelineRoute
  '/_auth/patients/$id/map-editor': typeof AuthPatientsIdMapEditorRoute
  '/_auth/patients/$id/medications': typeof AuthPatientsIdMedicationsRoute
  '/_auth/patients/$id/profile': typeof AuthPatientsIdProfileRoute
  '/_auth/patients/$id/': typeof AuthPatientsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/alerts'
    | '/data-dashboard'
    | '/data-export'
    | '/medications'
    | '/patients'
    | '/settings'
    | '/simulation'
    | '/iot/pins'
    | '/patients/$id'
    | '/settings/users'
    | '/patients/$id/alert-rules'
    | '/patients/$id/alerts'
    | '/patients/$id/health-timeline'
    | '/patients/$id/map-editor'
    | '/patients/$id/medications'
    | '/patients/$id/profile'
    | '/patients/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/alerts'
    | '/data-dashboard'
    | '/data-export'
    | '/medications'
    | '/patients'
    | '/settings'
    | '/simulation'
    | '/'
    | '/iot/pins'
    | '/settings/users'
    | '/patients/$id/alert-rules'
    | '/patients/$id/alerts'
    | '/patients/$id/health-timeline'
    | '/patients/$id/map-editor'
    | '/patients/$id/medications'
    | '/patients/$id/profile'
    | '/patients/$id'
  id:
    | '__root__'
    | '/_auth'
    | '/login'
    | '/_auth/alerts'
    | '/_auth/data-dashboard'
    | '/_auth/data-export'
    | '/_auth/medications'
    | '/_auth/patients'
    | '/_auth/settings'
    | '/_auth/simulation'
    | '/_auth/'
    | '/_auth/iot/pins'
    | '/_auth/patients/$id'
    | '/_auth/settings/users'
    | '/_auth/patients/$id/alert-rules'
    | '/_auth/patients/$id/alerts'
    | '/_auth/patients/$id/health-timeline'
    | '/_auth/patients/$id/map-editor'
    | '/_auth/patients/$id/medications'
    | '/_auth/patients/$id/profile'
    | '/_auth/patients/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/': {
      id: '/_auth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/simulation': {
      id: '/_auth/simulation'
      path: '/simulation'
      fullPath: '/simulation'
      preLoaderRoute: typeof AuthSimulationRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/settings': {
      id: '/_auth/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthSettingsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/patients': {
      id: '/_auth/patients'
      path: '/patients'
      fullPath: '/patients'
      preLoaderRoute: typeof AuthPatientsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/medications': {
      id: '/_auth/medications'
      path: '/medications'
      fullPath: '/medications'
      preLoaderRoute: typeof AuthMedicationsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/data-export': {
      id: '/_auth/data-export'
      path: '/data-export'
      fullPath: '/data-export'
      preLoaderRoute: typeof AuthDataExportRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/data-dashboard': {
      id: '/_auth/data-dashboard'
      path: '/data-dashboard'
      fullPath: '/data-dashboard'
      preLoaderRoute: typeof AuthDataDashboardRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/alerts': {
      id: '/_auth/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AuthAlertsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/settings/users': {
      id: '/_auth/settings/users'
      path: '/users'
      fullPath: '/settings/users'
      preLoaderRoute: typeof AuthSettingsUsersRouteImport
      parentRoute: typeof AuthSettingsRoute
    }
    '/_auth/patients/$id': {
      id: '/_auth/patients/$id'
      path: '/$id'
      fullPath: '/patients/$id'
      preLoaderRoute: typeof AuthPatientsIdRouteImport
      parentRoute: typeof AuthPatientsRoute
    }
    '/_auth/iot/pins': {
      id: '/_auth/iot/pins'
      path: '/iot/pins'
      fullPath: '/iot/pins'
      preLoaderRoute: typeof AuthIotPinsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/patients/$id/': {
      id: '/_auth/patients/$id/'
      path: '/'
      fullPath: '/patients/$id/'
      preLoaderRoute: typeof AuthPatientsIdIndexRouteImport
      parentRoute: typeof AuthPatientsIdRoute
    }
    '/_auth/patients/$id/profile': {
      id: '/_auth/patients/$id/profile'
      path: '/profile'
      fullPath: '/patients/$id/profile'
      preLoaderRoute: typeof AuthPatientsIdProfileRouteImport
      parentRoute: typeof AuthPatientsIdRoute
    }
    '/_auth/patients/$id/medications': {
      id: '/_auth/patients/$id/medications'
      path: '/medications'
      fullPath: '/patients/$id/medications'
      preLoaderRoute: typeof AuthPatientsIdMedicationsRouteImport
      parentRoute: typeof AuthPatientsIdRoute
    }
    '/_auth/patients/$id/map-editor': {
      id: '/_auth/patients/$id/map-editor'
      path: '/map-editor'
      fullPath: '/patients/$id/map-editor'
      preLoaderRoute: typeof AuthPatientsIdMapEditorRouteImport
      parentRoute: typeof AuthPatientsIdRoute
    }
    '/_auth/patients/$id/health-timeline': {
      id: '/_auth/patients/$id/health-timeline'
      path: '/health-timeline'
      fullPath: '/patients/$id/health-timeline'
      preLoaderRoute: typeof AuthPatientsIdHealthTimelineRouteImport
      parentRoute: typeof AuthPatientsIdRoute
    }
    '/_auth/patients/$id/alerts': {
      id: '/_auth/patients/$id/alerts'
      path: '/alerts'
      fullPath: '/patients/$id/alerts'
      preLoaderRoute: typeof AuthPatientsIdAlertsRouteImport
      parentRoute: typeof AuthPatientsIdRoute
    }
    '/_auth/patients/$id/alert-rules': {
      id: '/_auth/patients/$id/alert-rules'
      path: '/alert-rules'
      fullPath: '/patients/$id/alert-rules'
      preLoaderRoute: typeof AuthPatientsIdAlertRulesRouteImport
      parentRoute: typeof AuthPatientsIdRoute
    }
  }
}

interface AuthPatientsIdRouteChildren {
  AuthPatientsIdAlertRulesRoute: typeof AuthPatientsIdAlertRulesRoute
  AuthPatientsIdAlertsRoute: typeof AuthPatientsIdAlertsRoute
  AuthPatientsIdHealthTimelineRoute: typeof AuthPatientsIdHealthTimelineRoute
  AuthPatientsIdMapEditorRoute: typeof AuthPatientsIdMapEditorRoute
  AuthPatientsIdMedicationsRoute: typeof AuthPatientsIdMedicationsRoute
  AuthPatientsIdProfileRoute: typeof AuthPatientsIdProfileRoute
  AuthPatientsIdIndexRoute: typeof AuthPatientsIdIndexRoute
}

const AuthPatientsIdRouteChildren: AuthPatientsIdRouteChildren = {
  AuthPatientsIdAlertRulesRoute: AuthPatientsIdAlertRulesRoute,
  AuthPatientsIdAlertsRoute: AuthPatientsIdAlertsRoute,
  AuthPatientsIdHealthTimelineRoute: AuthPatientsIdHealthTimelineRoute,
  AuthPatientsIdMapEditorRoute: AuthPatientsIdMapEditorRoute,
  AuthPatientsIdMedicationsRoute: AuthPatientsIdMedicationsRoute,
  AuthPatientsIdProfileRoute: AuthPatientsIdProfileRoute,
  AuthPatientsIdIndexRoute: AuthPatientsIdIndexRoute,
}

const AuthPatientsIdRouteWithChildren = AuthPatientsIdRoute._addFileChildren(
  AuthPatientsIdRouteChildren,
)

interface AuthPatientsRouteChildren {
  AuthPatientsIdRoute: typeof AuthPatientsIdRouteWithChildren
}

const AuthPatientsRouteChildren: AuthPatientsRouteChildren = {
  AuthPatientsIdRoute: AuthPatientsIdRouteWithChildren,
}

const AuthPatientsRouteWithChildren = AuthPatientsRoute._addFileChildren(
  AuthPatientsRouteChildren,
)

interface AuthSettingsRouteChildren {
  AuthSettingsUsersRoute: typeof AuthSettingsUsersRoute
}

const AuthSettingsRouteChildren: AuthSettingsRouteChildren = {
  AuthSettingsUsersRoute: AuthSettingsUsersRoute,
}

const AuthSettingsRouteWithChildren = AuthSettingsRoute._addFileChildren(
  AuthSettingsRouteChildren,
)

interface AuthRouteChildren {
  AuthAlertsRoute: typeof AuthAlertsRoute
  AuthDataDashboardRoute: typeof AuthDataDashboardRoute
  AuthDataExportRoute: typeof AuthDataExportRoute
  AuthMedicationsRoute: typeof AuthMedicationsRoute
  AuthPatientsRoute: typeof AuthPatientsRouteWithChildren
  AuthSettingsRoute: typeof AuthSettingsRouteWithChildren
  AuthSimulationRoute: typeof AuthSimulationRoute
  AuthIndexRoute: typeof AuthIndexRoute
  AuthIotPinsRoute: typeof AuthIotPinsRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthAlertsRoute: AuthAlertsRoute,
  AuthDataDashboardRoute: AuthDataDashboardRoute,
  AuthDataExportRoute: AuthDataExportRoute,
  AuthMedicationsRoute: AuthMedicationsRoute,
  AuthPatientsRoute: AuthPatientsRouteWithChildren,
  AuthSettingsRoute: AuthSettingsRouteWithChildren,
  AuthSimulationRoute: AuthSimulationRoute,
  AuthIndexRoute: AuthIndexRoute,
  AuthIotPinsRoute: AuthIotPinsRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
